services:

  server:
    image: gvenzl/${ORACLE_REPO:-oracle-free}:${ORACLE_VERSION}
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
    volumes:
      - data:/opt/oracle/oradata
    ports:
      - ${ORACLE_PORT:-1521}:1521
    healthcheck:
      test: healthcheck.sh
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  data:
